# Generated by Django 3.1 on 2020-09-05 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('Phones & Accessories', 'Phones & Accessories'), ('Kitchen Tools', 'Kitchen Tools'), ('Baby Products', 'Baby Products'), ("Women's Clothing", "Women's Clothing"), ("Men's Clothing", "Men's Clothing"), ('Beauty, Hair & Health', 'Beauty, Hair & Health'), ('Shoes', 'Shoes'), ('Bags', 'Bags'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Home Improvement Tools', 'Home Improvement Tools'), ('Gadgets', 'Gadgets')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('total_units', models.IntegerField(default=1)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review', to='accounts.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'review',
                'db_table': 'Review',
            },
        ),
    ]
