# Generated by Django 3.1 on 2020-08-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(choices=[('Phones & Accessories', 'Phones & Accessories'), ('Kitchen Tools', 'Kitchen Tools'), ('Baby Products', 'Baby Products'), ("Women's Clothing", "Women's Clothing"), ("Men's Clothing", "Men's Clothing"), ('Beauty, Hair & Health', 'Beauty, Hair & Health'), ('Shoes', 'Shoes'), ('Bags', 'Bags'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Home Improvement Tools', 'Home Improvement Tools'), ('Gadgets', 'Gadgets')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'products',
                'db_table': 'Products',
            },
        ),
    ]
