# Generated by Django 3.1 on 2020-09-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
